### ISSUE TITLE
Choose between several join messages

### ISSUE THREAD

**Issue by dionmeraki** [Insprill/custom-join-messages#70]
### Describe the Feature

As a player, I want to be able to choose several join messages and enable/disable them from a GUI.

This can easily be made by a plugin like CommandPanels, but I'll need a command to toggle a specific join status for a player e.g /cjm toggle on <identifier> <player> 

### Provide Reasoning

I really want to be able to allow my players to choose from different join messages

### Checklist

- [x] I have searched the [issue tracker](https://github.com/Insprill/custom-join-messages/issues) to ensure there are no similar feature requests
- [x] I have read the wiki to ensure this isn't already possible
- [ ] I ticked all of the boxes without actually reading them

**Comment by Zarkness2** [comment]
@dionmeraki I do not know if I understood you well, but you mean that you have for example and you want the user to choose between those 2 messages?

If you mean that, you can do it by giving and removing the permission, for example the user has activated the first message you in the menu with commandpanels in the item of the message 2, what you have to do is to remove the permission cjm.msg.pub.join.1 and give the permission cjm.msg.pub.join.2.

```yml
  Join:
    1:
      Permission: cjm.msg.pub.join.1
      Messages:
        1:
          - "#969795[#dff1bc+#969795] #a7cb83%name% #dcf9bfHas joined the server"
    2:
      Permission: cjm.msg.pub.join.2
      Messages:
        1:
          - "#969795[#dff1bc+#969795] #a7cb83%name%"
```
